#!/usr/bin/env python

import argparse, syslog, daemon, sys

from appletlib.app         import Application
from weatherapplet.weather import WeatherIndicator

def main(argdict):
    app = Application("mechnich","weather-applet")
    app.init(argdict)
    i = [ WeatherIndicator() ]
    syslog.syslog( syslog.LOG_INFO, "INFO   startup complete");
    sys.exit(app.exec_())

if __name__ == "__main__":
    args = Application.parseCommandLine('Weather applet')
    argdict = { 'verbosity': args.verbosity, 'daemon': args.daemon }
    if args.daemon:
        with daemon.DaemonContext():
            main(argdict)
    else:
        main(argdict)
